In [30]:
import sys
import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# This should eventually be moved to an __init__.py file 
sys.path.insert(0, './functions/')
sys.path.insert(0, './data/')
import read_data as rd
import cost 
import ammortization
import replacement



%matplotlib inline
# %load_ext autoreload
%autoreload 2

In [48]:
plant_data, cost_data, cf_data, age_data = rd.read_data(os.getcwd())

In [54]:
p1_fuel = plant_data.loc[0, "primary_fuel"] 
p1_gen = plant_data.loc[0, "generation"] # kwh
p1_cap = plant_data.loc[0, "capacity"]*1000 # kw
p1_cons = plant_data.loc[0, "fuel_consumption"]*1e6 # btu
p1_age = 2017-plant_data.loc[0, "commissioning_year"]

p1_capital = cost_data.loc[p1_fuel, "capital_cost_per_kw"]*p1_cap
p1_lifetime = age_data.loc[p1_fuel, "pay_off_age"]

In [63]:
cost.remaining_cost(p1_capital, p1_age, 0.06, 30)
plant_data.loc[0, "primary_fuel"]

0       17.000000
1       26.000000
2       20.868893
3       11.000000
4       48.000000
          ...
3875          NaN
3876          NaN
3877          NaN
3878          NaN
3879          NaN
Name: commissioning_year, Length: 3880, dtype: float64

In [67]:
test_cost_data = cost_data.to_dict()
cost_data

,capital_cost_per_kw,fixed_om_per_kw_year,variable_om_per_mwh,discount_rate,fuel_price_per_btu
primary_fuel,,,,,
Coal,3676,40.580,4.50,0.06,0.000003
Gas,958,12.200,1.87,0.06,0.000002
Oil,1810,35.160,5.69,0.06,0.000012
Solar,1313,15.250,0.00,0.06,0.000000
Wind,1265,26.340,0.00,0.06,0.000000
Waste,1563,20.100,6.20,0.06,0.000000
Hydro,5316,29.860,0.00,0.06,0.000000
Geothermal,2521,128.544,1.16,0.06,0.000000
CSP,7221,85.400,0.00,0.06,0.000000
Nuclear,6041,121.640,2.37,0.06,0.000000
Biomass,4097,125.720,4.83,0.06,0.000000

In [58]:
test_df = plant_data.copy()
test_func = np.vectorize(cost.remaining_cost)

In [65]:
test_df["remaining_cost"] = test_func(plant_data["capacity"], 2017-plant_data["commissioning_year"], 0.06, 30)
test_df

C:\Users\jhuster\Anaconda3\lib\site-packages\numpy\lib\function_base.py:2197: RuntimeWarning: invalid value encountered in remaining_cost (vectorized)
  outputs = ufunc(*inputs)

,name,capacity,primary_fuel,commissioning_year,state,generation,fuel_consumption,emissions,remaining_cost
0,1515 s caron road,4.2,Gas,2000.000000,IL,2.400000e+04,394.0,20.909770,2.701179
1,191 peachtree tower,2.4,Oil,1991.000000,GA,0.000000e+00,28.0,2.048499,0.604167
2,491 e 48th street,161.7,Gas,1996.131107,MI,2.110300e+07,262600.0,13936.308430,80.783659
3,500mw cc,528.0,Gas,2006.000000,NY,2.446465e+09,18679059.0,997255.075800,428.010009
4,59th street,17.1,Gas,1969.000000,NY,1.190000e+05,1829.0,97.065911,0.000000
...,...,...,...,...,...,...,...,...,...
3875,wolf run energy,NaN,NaN,NaN,PA,2.393000e+07,215897.0,11457.757730,NaN
3876,woodland pulp llc,NaN,NaN,NaN,ME,6.171301e+07,273459.0,95698.231190,NaN
3877,works 4,NaN,NaN,NaN,TX,1.140000e+05,1050.0,76.818697,NaN
3878,yellowstone energy lp,NaN,NaN,NaN,MT,4.496906e+08,4702405.0,753994.300500,NaN
3879,york cogen facility,NaN,NaN,NaN,PA,0.000000e+00,5569.0,295.549511,NaN